# Generated by Django 5.0.3 on 2024-05-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reguser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('course_field', models.CharField(blank=True, choices=[('certificate in health science', 'Certificate in Health Science'), ('certificate in applied technology', 'Certificate in Applied Technology'), ('bachelor of inforamtion technology', 'Bachelor of Inforamtion Technology'), ('bachelor in business technology', 'Bachelor of Business Technology'), ('master of public health', 'Master of Public Health')], max_length=50, null=True)),
                ('entry_scheme', models.CharField(blank=True, choices=[('a-level certificate', 'A-Level Certificate'), ('adult/mature learning', 'Adult/Mature Learning'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('bachelors', 'Bachelors')], max_length=50, null=True)),
                ('intake', models.CharField(blank=True, choices=[('january intake', 'January Intake'), ('may intake', 'May Intake'), ('august intake', 'August')], max_length=50, null=True)),
                ('sponsor', models.CharField(blank=True, choices=[('private', 'Private'), ('government', 'Government'), ('bursary', 'Bursary')], max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=50, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('residence', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
