# Generated by Django 5.0.3 on 2024-05-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assessapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reguser',
            old_name='course_field',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='reguser',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='reguser',
            old_name='sponsor',
            new_name='sponsorship',
        ),
    ]
