# Generated by Django 5.0.3 on 2024-05-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assessapp', '0002_rename_course_field_reguser_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=50, null=True),
        ),
    ]
