# Generated by Django 5.0.3 on 2024-05-17 11:46

import Assessapp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assessapp', '0003_alter_reguser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(3), Assessapp.models.validate_letters]),
        ),
        migrations.AlterField(
            model_name='reguser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(3), Assessapp.models.validate_letters]),
        ),
    ]
